[package]
name = "picprime"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[[bin]]
name = "picprime"
path = "picprime.rs"

[dependencies]
glass_pumpkin = "0"
num-bigint = "*"
rand = "*"
